name: Configure CI
description: Performs the initial configuration of the CI environment

inputs:
  java:
    description: The Java version to use
    required: false
    default: | # https://github.com/actions/setup-java#install-multiple-jdks
      11
  distribution:
    description: The distribution to use
    required: false
    default: 'temurin'

runs:
  using: composite

  steps:
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: ${{ inputs.java }}
        distribution: ${{ inputs.distribution }}
        cache: 'gradle'

    - name: Setup Android SDK
      uses: android-actions/setup-android@7c5672355aaa8fde5f97a91aa9a99616d1ace6bc # pin@2.0.10
