name: Publish Release

on:
  workflow_dispatch:
    inputs:
      branch:
        description: The branch to release from.
        required: true
        default: main

permissions:
  contents: read

jobs:
  publish:
    name: Publish to Maven Central
    runs-on: ubuntu-latest
    environment: release

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.branch }}

      - uses: ./.github/actions/setup

      - uses: gradle/gradle-build-action@ef76a971e2fa3f867b617efd72f2fbd72cf6f8bc # pin@2.8.0
        with:
          arguments: clean assemble -PisSnapshot=false

      - uses: gradle/gradle-build-action@ef76a971e2fa3f867b617efd72f2fbd72cf6f8bc # pin@2.8.0
        with:
          arguments: exportVersion -PisSnapshot=false

      - uses: gradle/gradle-build-action@ef76a971e2fa3f867b617efd72f2fbd72cf6f8bc # pin@2.8.0
        with:
          arguments: |
            publishAndroidLibraryPublicationToMavenRepository
            -PossrhUsername="${{ secrets.OSSR_USERNAME }}"
            -PossrhPassword="${{ secrets.OSSR_PASSWORD }}"
            -PsigningKey="${{ secrets.SIGNING_KEY }}"
            -PsigningPassword="${{ secrets.SIGNING_PASSWORD }}"
            -PisSnapshot=false"
