name: Build and Test

on:
  merge_group:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  unit:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup

      - run: ./gradlew testReleaseUnitTest --console=plain --max-workers=1 --no-daemon

      - uses: codecov/codecov-action@eaaf4bedf32dbdc6b720b63067d99c4d77d6047d # pin@3.1.4

      - uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce
        if: ${{ failure() }}
        with:
          name: 'Test Result'
          path: /home/runner/work/Auth0.Android/Auth0.Android/auth0/build/reports/tests/testDebugUnitTest/index.html


      - uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce
        if: ${{ failure() }}
        with:
          name: 'Test Result'
          path: /home/runner/work/Auth0.Android/Auth0.Android/auth0/build/reports/tests/testReleaseUnitTest/index.html